apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-availability.my-apps.tap.20240318212725.0.0+build.6aff574
spec:
  refName: where-for-dinner-availability.my-apps.tap
  version: 20240318212725.0.0+build.6aff574
  releaseNotes: |
    Release v20240318212725.0.0+build.6aff574 of package where-for-dinner-availability.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tap-ci/ci-pipeline/apps-18-03-2024-16-42-04-527275657/where-for-dinner-availability-my-apps-bundle@sha256:3626aba3dc1b4506dfcd6a520b2700fa02912cdb87cfa905b044c843834fee40
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

